import { supabaseAdmin } from "@/lib/supabase-admin"

const SYSTEM_STATE_COMPANY = "__falco_system_state__"
const INVENTORY_KEY = "dialer_inventory"
const INVENTORY_EMAIL = `state+${INVENTORY_KEY}@falco.local`

export type DialerInventoryLead = {
  key: string
  slug: string
  leadKey: string
  address: string
  county: string
  state: string
  distressType: string
  saleStatus: string
  currentSaleDate: string
  originalSaleDate: string
  auctionReadiness: string
  equityBand: string
  dtsDays: number | null
  falcoScore: number | null
  firstSeenAt: string
  ownerName: string
  ownerMail: string
  ownerPhonePrimary: string
  ownerPhoneSecondary: string
  ownerPhoneDncStatus: string
  saleControllerName: string
  saleControllerPhonePrimary: string
  trusteePhonePublic: string
  noticePhone: string
  mortgageLender: string
  mortgageDate: string
  mortgageAmount: number | null
  lastSaleDate: string
  avmLow: number | null
  avmMid: number | null
  avmHigh: number | null
  beds: number | null
  baths: number | null
  buildingAreaSqft: number | null
  yearBuilt: number | null
  vaultSlug: string | null
  packetUrl: string | null
  packetLabel: string | null
  dataCompleteness?: "full" | "solid" | "thin"
  missingFields?: string[]
  /** Twilio Lookup line type: 'mobile' | 'landline' | 'fixedVoip' | 'nonFixedVoip' | 'fixed_line_or_mobile' | etc. Empty if unvalidated. */
  phoneLineType?: string
  /** Twilio Lookup carrier name (e.g. 'T-Mobile USA'). */
  phoneCarrier?: string
  /** True if Twilio Lookup confirmed the number is valid (carrier known). */
  phoneValidated?: boolean
  /** True if the primary phone is on BatchData's DNC list. */
  phoneDnc?: boolean
  /** Count of additional candidate phones in BatchData skip-trace
   *  beyond the primary. Useful when primary doesn't ring. */
  alternatePhoneCount?: number
  /** Full BatchData phone candidates (every number we've pulled for
   *  this property + per-phone DNC, line-type, and confidence). The
   *  dialer surfaces these as fallbacks when the primary doesn't
   *  connect. Does not include the primary phone itself. */
  alternatePhones?: AlternatePhone[]
  /** True if mortgage_balance came from a defensible source (ROD-verified, HMDA-anchored, nashville_ledger). */
  mortgageDefensible?: boolean
  /** Lender name from ROD or HMDA (with FFIEC panel fallback). */
  mortgageLenderResolved?: string
  /** Year the original loan was originated (HMDA match_year or ROD doc date). */
  mortgageOriginationYear?: number
  /** Original principal at origination (vs. mortgageAmount which is current/amortized). */
  mortgageOriginalPrincipal?: number
  /** Annual interest rate % from HMDA (when available). */
  mortgageRatePct?: number
  /** Source confidence 0–1 for the mortgage signal (0.85 ROD, 0.65–0.85 HMDA). */
  mortgageConfidence?: number
  /** Estimated equity = AVM − amortized current balance. */
  equityAmount?: number
  /** Distress signal count from distress_stack (how many distress flags fire). */
  distressSignalCount?: number
  /** Decision-engine action: PROMOTE_HOT / PROMOTE_WARM / REJECT / etc. */
  decisionAction?: string
  /** Pitch bucket — which sales motion fits this lead. See classifyPitchBucket. */
  pitchBucket?: PitchBucket
  /** Manual trustee-sale status flag set via /api/dialer/[slug]/sale-status.
   *  Distinct from the auction-listing `saleStatus` field above. */
  trusteeSaleStatus?: "cancelled" | "postponed" | "ran" | "reinstated"
  trusteeSaleStatusNote?: string
  trusteeSaleStatusUpdatedAt?: string
}

/**
 * Sales motion buckets — which conversation fits this lead.
 * Generated by classifyPitchBucket() from distress_type + equity ratio
 * + owner type. Drives the lead-detail "Pitch" panel and per-bucket
 * math/outreach templates.
 *
 *  EQUITY_PROTECT     PRE_FC + ≥20% equity. Math sheet first (gold path).
 *  LLC_INVESTOR       Owner is LLC/Inc/Corp. Investor-to-investor terms.
 *  CODE_VIOLATION     Metro Codes / Hamilton / Memphis violations.
 *  LOW_EQUITY_FC      PRE_FC but <20% equity. Stop-the-sale + relocation.
 *  PROBATE            Estate property, talking to executor.
 *  FSBO               Owner already trying to sell. Auction-vs-MLS pitch.
 *  BANKRUPTCY         Chapter 7/13. Trustee + attorney involved.
 *  UNDERWATER         Mortgage > AVM. Short-sale / DIL / cash-for-keys.
 *  UNCLASSIFIED       Lead missing distress signal or owner data.
 */
export type PitchBucket =
  | "EQUITY_PROTECT"
  | "LLC_INVESTOR"
  | "CODE_VIOLATION"
  | "LOW_EQUITY_FC"
  | "PROBATE"
  | "FSBO"
  | "BANKRUPTCY"
  | "UNDERWATER"
  | "UNCLASSIFIED"

const LLC_MARKERS = [
  " LLC", " L.L.C", " INC", " CORP", " COMPANY", " CO.",
  " TRUST", " LP ", " LP,", " L.P.", " LLP",
  " HOLDINGS", " PROPERTIES", " PARTNERS", " GROUP",
  " ENTERPRISES", " MANAGEMENT",
] as const

function looksLikeEntity(name: string | null | undefined): boolean {
  if (!name) return false
  const padded = " " + name.toUpperCase() + " "
  return LLC_MARKERS.some((m) => padded.includes(m))
}

export function classifyPitchBucket(args: {
  distressType: string | null | undefined
  ownerName: string | null | undefined
  propertyValue: number | null | undefined
  mortgageBalance: number | null | undefined
}): PitchBucket {
  const dt = (args.distressType || "").toUpperCase()
  const owner = args.ownerName || ""
  const pv = args.propertyValue || 0
  const mb = args.mortgageBalance || 0
  const equityRatio = pv > 0 && mb > 0 ? (pv - mb) / pv : null

  // LLC/entity wins regardless of distress — different motion entirely
  if (looksLikeEntity(owner)) return "LLC_INVESTOR"

  // Underwater wins next — math sheet would deflate the call
  if (equityRatio !== null && equityRatio < 0) return "UNDERWATER"

  // Distress-type-driven branches
  if (dt === "PROBATE") return "PROBATE"
  if (dt === "CODE_VIOLATION") return "CODE_VIOLATION"
  if (dt === "TAX_LIEN") return "CODE_VIOLATION"  // similar liability-transfer pitch
  if (dt === "BANKRUPTCY") return "BANKRUPTCY"
  if (dt === "FSBO") return "FSBO"

  // Foreclosure family — split by equity
  if (
    dt === "PRE_FORECLOSURE" ||
    dt === "TRUSTEE_NOTICE" ||
    dt === "FORECLOSURE" ||
    dt === "LIS_PENDENS"
  ) {
    if (equityRatio !== null && equityRatio >= 0.2) return "EQUITY_PROTECT"
    if (equityRatio !== null && equityRatio < 0.2) return "LOW_EQUITY_FC"
    // No equity data — default to EQUITY_PROTECT, rep can downgrade if needed
    return "EQUITY_PROTECT"
  }

  return "UNCLASSIFIED"
}

export type DialerInventorySnapshot = {
  generatedAt: string
  leads: DialerInventoryLead[]
}

/** Raw snapshot loader — reads the JSON blob in partner_access_requests.
 *  Used as a structural-data backup. Phone/email/AVM in the snapshot may
 *  be stale; loadDialerInventory() merges fresh data from homeowner_requests
 *  on top before returning. */
async function loadRawSnapshot(): Promise<DialerInventorySnapshot | null> {
  if (!supabaseAdmin) return null

  const { data, error } = await supabaseAdmin
    .from("partner_access_requests")
    .select("notes, created_at")
    .eq("company", SYSTEM_STATE_COMPANY)
    .eq("status", "state_snapshot")
    .eq("email", INVENTORY_EMAIL)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle()

  if (error) {
    if (error.code !== "PGRST116") {
      console.error("loadRawSnapshot error:", error.message)
    }
    return null
  }
  if (!data?.notes) return null

  try {
    const envelope = JSON.parse(data.notes as string)
    const payload = envelope?.payload
    if (!payload || !Array.isArray(payload.leads)) return null
    return {
      generatedAt: String(envelope.updatedAt ?? payload.generatedAt ?? ""),
      leads: payload.leads as DialerInventoryLead[],
    }
  } catch (err) {
    console.error("loadRawSnapshot parse error:", err)
    return null
  }
}

/** A row from homeowner_requests with the fields we want to merge into
 *  the dialer inventory view. */
type HomeownerRequestRow = {
  pipeline_lead_key: string | null
  property_address: string | null
  county: string | null
  email: string | null
  phone: string | null
  full_name: string | null
  owner_name_records: string | null
  property_value: number | null
  beds: number | null
  baths: number | null
  sqft: number | null
  year_built: number | null
  trustee_sale_date: string | null
  distress_type: string | null
  mortgage_balance: number | null
  last_sale_date: string | null
  pipeline_score: number | null
  submitted_at: string | null
  phone_metadata: Record<string, unknown> | null
}

/** Inspect phone_metadata to derive every field surfaced on the queue
 *  + lead-detail UI: phone validation, line type, mortgage source,
 *  amortized balance, lender, equity, etc. Source-of-truth derivation
 *  so callers don't re-implement these rules. */
/** A single phone-number candidate from BatchData skip-trace, with the
 *  per-phone metadata that determines whether it's worth dialing. */
export type AlternatePhone = {
  number: string
  /** Land Line / Mobile / VoIP / Wireless / etc. — verbatim from BatchData. */
  lineType?: string
  /** True if BatchData flagged this specific number as DNC. */
  dnc?: boolean
  /** 0–100 BatchData confidence score for the number. */
  score?: number
  /** True if BatchData has tested the number for reachability. */
  tested?: boolean
  /** True if the test came back "reachable". */
  reachable?: boolean
  /** Twilio Lookup carrier when an alternate has been validated.
   *  Most alternates won't have this — Twilio runs primary-only. */
  carrier?: string
}

type PhoneMetaDerived = {
  phoneLineType?: string
  phoneCarrier?: string
  phoneValidated?: boolean
  phoneDnc?: boolean
  alternatePhoneCount?: number
  alternatePhones?: AlternatePhone[]
  mortgageDefensible?: boolean
  mortgageLenderResolved?: string
  mortgageOriginationYear?: number
  mortgageOriginalPrincipal?: number
  mortgageRatePct?: number
  mortgageConfidence?: number
  equityAmount?: number
  distressSignalCount?: number
  decisionAction?: string
  /** Manual trustee-sale status flag set via
   *  /api/dialer/[slug]/sale-status. Distinct from the auction-listing
   *  saleStatus on DialerInventoryLead.
   *
   *  "cancelled" = lender withdrew the notice (deprioritize from
   *  urgency pitches, neutral math sheet hero).
   *  "postponed" = pushed to a new date (trustee_sale_date is updated).
   *  "ran" = trustee sale already happened.
   *  "reinstated" = borrower brought arrears current. */
  trusteeSaleStatus?: "cancelled" | "postponed" | "ran" | "reinstated"
  trusteeSaleStatusNote?: string
  trusteeSaleStatusUpdatedAt?: string
}

function deriveFromPhoneMetadata(
  pm: Record<string, unknown> | null | undefined,
  avmMid: number | null
): PhoneMetaDerived & { amortizedCurrentBalance?: number } {
  if (!pm || typeof pm !== "object") return {}
  const obj = pm as Record<string, unknown>
  const out: ReturnType<typeof deriveFromPhoneMetadata> = {}

  // Phone validation (Twilio Lookup)
  const tl = obj.twilio_lookup as Record<string, unknown> | undefined
  if (tl && typeof tl === "object") {
    out.phoneValidated = tl.valid === true
    if (typeof tl.line_type === "string") out.phoneLineType = tl.line_type
    if (typeof tl.carrier_name === "string") out.phoneCarrier = tl.carrier_name as string
  }

  // BatchData primary DNC + alternate count + full alternate list
  const bd = obj.batchdata_skip_trace as Record<string, unknown> | undefined
  if (bd && typeof bd === "object") {
    if (bd.primary_dnc === true) out.phoneDnc = true
    const all = bd.all_phones as unknown[] | undefined
    if (Array.isArray(all)) {
      out.alternatePhoneCount = Math.max(0, all.length - 1)
      // Surface every phone candidate the dialer can fall through to
      // when the primary doesn't connect. Strip leading +1 / non-digits
      // and dedupe by 10-digit form. Caller-side rendering handles
      // formatting + tel/sms links.
      const seen = new Set<string>()
      const phones: AlternatePhone[] = []
      for (const raw of all) {
        if (!raw || typeof raw !== "object") continue
        const r = raw as Record<string, unknown>
        const numStr =
          typeof r.phone === "string"
            ? r.phone
            : typeof r.number === "string"
            ? (r.number as string)
            : ""
        const digits = numStr.replace(/\D/g, "")
        const tenDigit =
          digits.length === 11 && digits.startsWith("1")
            ? digits.slice(1)
            : digits
        if (tenDigit.length !== 10) continue
        if (seen.has(tenDigit)) continue
        seen.add(tenDigit)
        phones.push({
          number: tenDigit,
          lineType:
            typeof r.phone_type === "string"
              ? (r.phone_type as string)
              : typeof r.line_type === "string"
              ? (r.line_type as string)
              : undefined,
          dnc: r.dnc === true,
          score: typeof r.score === "number" ? (r.score as number) : undefined,
          tested: r.tested === true,
          reachable: r.reachable === true,
        })
      }
      if (phones.length > 0) out.alternatePhones = phones
    }
  }

  // Mortgage source — ROD wins, then HMDA-anchored, then nashville_ledger
  const rod = obj.rod_lookup as Record<string, unknown> | undefined
  const sig = obj.mortgage_signal as Record<string, unknown> | undefined
  if (rod && typeof rod === "object") {
    out.mortgageDefensible = true
    out.mortgageConfidence = 0.85
    if (typeof rod.lender === "string") out.mortgageLenderResolved = rod.lender as string
    if (typeof rod.original_principal === "number") {
      out.mortgageOriginalPrincipal = rod.original_principal as number
    }
    if (typeof rod.rate_pct === "number") {
      out.mortgageRatePct = rod.rate_pct as number
    }
    const docDate = rod.document_date as string | undefined
    if (docDate && typeof docDate === "string") {
      const m = /^(\d{4})/.exec(docDate)
      if (m) out.mortgageOriginationYear = parseInt(m[1], 10)
    }
  }
  if (sig && typeof sig === "object") {
    const src = sig.source as string | undefined
    const saleAnchored = !!sig.sale_anchored
    const yearAnchored = !!sig.year_anchored
    if (
      src === "ustitlesearch_rod" ||
      src === "nashville_ledger_extracted" ||
      (src === "hmda_match" && (saleAnchored || yearAnchored))
    ) {
      out.mortgageDefensible = true
    }
    if (!out.mortgageLenderResolved && typeof sig.lender === "string") {
      out.mortgageLenderResolved = sig.lender as string
    }
    if (!out.mortgageOriginationYear && sig.match_year) {
      const mm = parseInt(String(sig.match_year), 10)
      if (!Number.isNaN(mm)) out.mortgageOriginationYear = mm
    }
    if (!out.mortgageOriginalPrincipal && typeof sig.amount === "number") {
      out.mortgageOriginalPrincipal = sig.amount as number
    }
    if (!out.mortgageRatePct && sig.interest_rate) {
      const rr = parseFloat(String(sig.interest_rate))
      if (!Number.isNaN(rr)) out.mortgageRatePct = rr
    }
    if (typeof sig.confidence === "number") {
      out.mortgageConfidence = Math.max(out.mortgageConfidence ?? 0, sig.confidence as number)
    }
  }

  // Amortized current balance (from mortgage_amortizer_bot)
  const amort = obj.mortgage_balance_amortized as Record<string, unknown> | undefined
  if (amort && typeof amort === "object") {
    if (typeof amort.current_balance === "number") {
      out.amortizedCurrentBalance = amort.current_balance as number
    }
    if (!out.mortgageOriginalPrincipal && typeof amort.original_principal === "number") {
      out.mortgageOriginalPrincipal = amort.original_principal as number
    }
    if (!out.mortgageRatePct && typeof amort.rate_pct === "number") {
      out.mortgageRatePct = amort.rate_pct as number
    }
    if (!out.mortgageOriginationYear && typeof amort.origination_year === "number") {
      out.mortgageOriginationYear = amort.origination_year as number
    }
    if (typeof amort.equity_estimate === "number") {
      out.equityAmount = amort.equity_estimate as number
    }
  }
  // Fallback equity calc when amortizer hasn't run
  if (out.equityAmount === undefined && avmMid && out.amortizedCurrentBalance) {
    out.equityAmount = avmMid - out.amortizedCurrentBalance
  }

  // Distress stack (signal count)
  const stack = obj.distress_stack as Record<string, unknown> | undefined
  if (stack && typeof stack === "object" && typeof stack.signal_count === "number") {
    out.distressSignalCount = stack.signal_count as number
  }

  // Decision-engine action
  const de = obj.decision_engine as Record<string, unknown> | undefined
  if (de && typeof de === "object" && typeof de.action === "string") {
    out.decisionAction = de.action as string
  }

  // Manual sale-status flag (set via /api/dialer/[slug]/sale-status)
  const ss = obj.sale_status as Record<string, unknown> | undefined
  if (ss && typeof ss === "object") {
    const status = ss.status
    if (
      status === "cancelled" ||
      status === "postponed" ||
      status === "ran" ||
      status === "reinstated"
    ) {
      out.trusteeSaleStatus = status
    }
    if (typeof ss.note === "string") out.trusteeSaleStatusNote = ss.note
    if (typeof ss.updated_at === "string") {
      out.trusteeSaleStatusUpdatedAt = ss.updated_at
    }
  }

  return out
}

async function loadHomeownerRequestsBots(): Promise<HomeownerRequestRow[]> {
  if (!supabaseAdmin) return []
  const { data, error } = await supabaseAdmin
    .from("homeowner_requests")
    .select(
      "pipeline_lead_key, property_address, county, email, phone, full_name, owner_name_records, property_value, beds, baths, sqft, year_built, trustee_sale_date, distress_type, mortgage_balance, last_sale_date, pipeline_score, submitted_at, phone_metadata"
    )
    .eq("source", "bot")
  if (error) {
    console.error("loadHomeownerRequestsBots error:", error.message)
    return []
  }
  return (data || []) as unknown as HomeownerRequestRow[]
}

function nonEmpty<T>(v: T | null | undefined | ""): T | null {
  return v === null || v === undefined || v === "" ? null : (v as T)
}

/** Build a DialerInventoryLead from a homeowner_requests row, optionally
 *  enriched with structural fields from a matching snapshot lead. */
function buildLeadFromHR(
  hr: HomeownerRequestRow,
  snap: DialerInventoryLead | null
): DialerInventoryLead {
  const key = (hr.pipeline_lead_key || snap?.key || "").trim()
  const ownerName =
    nonEmpty(hr.owner_name_records) ?? nonEmpty(hr.full_name) ?? snap?.ownerName ?? ""

  return {
    // Identifiers — prefer snapshot's keys (matches existing routing)
    key: snap?.key || key,
    slug: snap?.slug || key,
    leadKey: snap?.leadKey || key,
    // Address / locality
    address: hr.property_address || snap?.address || "",
    county: hr.county || snap?.county || "",
    state: snap?.state || "TN",
    // Distress
    distressType: hr.distress_type || snap?.distressType || "",
    saleStatus: snap?.saleStatus || "",
    currentSaleDate: hr.trustee_sale_date || snap?.currentSaleDate || "",
    originalSaleDate: snap?.originalSaleDate || "",
    auctionReadiness: snap?.auctionReadiness || "",
    equityBand: snap?.equityBand || "",
    dtsDays: snap?.dtsDays ?? null,
    falcoScore: hr.pipeline_score ?? snap?.falcoScore ?? null,
    firstSeenAt: snap?.firstSeenAt || hr.submitted_at || "",
    // Contact — HR is authoritative (BatchData skip-trace)
    ownerName,
    ownerMail: nonEmpty(hr.email) ?? snap?.ownerMail ?? "",
    ownerPhonePrimary: nonEmpty(hr.phone) ?? snap?.ownerPhonePrimary ?? "",
    ownerPhoneSecondary: snap?.ownerPhoneSecondary || "",
    ownerPhoneDncStatus: snap?.ownerPhoneDncStatus || "",
    // Sale controller (snapshot only)
    saleControllerName: snap?.saleControllerName || "",
    saleControllerPhonePrimary: snap?.saleControllerPhonePrimary || "",
    trusteePhonePublic: snap?.trusteePhonePublic || "",
    noticePhone: snap?.noticePhone || "",
    // Mortgage — HR has balance, snapshot has lender/date
    mortgageLender: snap?.mortgageLender || "",
    mortgageDate: snap?.mortgageDate || "",
    mortgageAmount: hr.mortgage_balance ?? snap?.mortgageAmount ?? null,
    // Property characteristics — HR is fresh from BatchData
    lastSaleDate: hr.last_sale_date || snap?.lastSaleDate || "",
    avmLow: snap?.avmLow ?? null,
    avmMid: hr.property_value ?? snap?.avmMid ?? null,
    avmHigh: snap?.avmHigh ?? null,
    beds: hr.beds ?? snap?.beds ?? null,
    baths: hr.baths ?? snap?.baths ?? null,
    buildingAreaSqft: hr.sqft ?? snap?.buildingAreaSqft ?? null,
    yearBuilt: hr.year_built ?? snap?.yearBuilt ?? null,
    // Vault / packet
    vaultSlug: snap?.vaultSlug ?? null,
    packetUrl: snap?.packetUrl ?? null,
    packetLabel: snap?.packetLabel ?? null,
    dataCompleteness: snap?.dataCompleteness,
    missingFields: snap?.missingFields,
    // Phone validation + mortgage source + amortization, all derived
    // from the HR row's phone_metadata blob (single source of truth).
    // Strip amortizedCurrentBalance — that's already in mortgageAmount
    // because the amortizer wrote it back to the column.
    ...((): PhoneMetaDerived => {
      const d = deriveFromPhoneMetadata(hr.phone_metadata, hr.property_value)
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { amortizedCurrentBalance: _, ...rest } = d
      return rest
    })(),
    // Sales motion bucket — drives lead-detail Pitch panel
    pitchBucket: classifyPitchBucket({
      distressType: hr.distress_type,
      ownerName: ownerName,
      propertyValue: hr.property_value,
      mortgageBalance: hr.mortgage_balance,
    }),
  }
}

/** Public loader: returns the dialer inventory with FRESH data from
 *  homeowner_requests merged over the snapshot.
 *
 *  Source of truth: homeowner_requests (post-dedup, post-skip-trace,
 *  post-BatchData enrichment). Snapshot provides structural backfill
 *  for fields we don't store in HR (sale controller, beds/baths/etc.
 *  not always present, packet URLs).
 */
export async function loadDialerInventory(): Promise<DialerInventorySnapshot | null> {
  const [snapshot, hrRows] = await Promise.all([
    loadRawSnapshot(),
    loadHomeownerRequestsBots(),
  ])

  // If neither source returned anything, bail
  if (!snapshot && hrRows.length === 0) return null

  // Build a map of snapshot leads by key for fast lookup
  const snapByKey = new Map<string, DialerInventoryLead>()
  if (snapshot) {
    for (const lead of snapshot.leads) {
      const keys = [lead.key, lead.slug, lead.leadKey, lead.vaultSlug].filter(
        (k) => !!k
      )
      for (const k of keys) {
        if (k) snapByKey.set(String(k), lead)
      }
    }
  }

  // For every HR bot row, build the merged lead. HR is the source of truth
  // for which leads exist (post-dedup) and for fresh contact/AVM data.
  // No filtering here — direct lead-detail navigation must still resolve
  // foreclosed leads so the caller can close them out in the workflow. Queue
  // views filter via isLeadActive() below.
  const merged: DialerInventoryLead[] = hrRows
    .filter((r) => !!r.pipeline_lead_key)
    .map((r) => {
      const snap = snapByKey.get(r.pipeline_lead_key as string) ?? null
      return buildLeadFromHR(r, snap)
    })

  return {
    generatedAt: new Date().toISOString(),
    leads: merged,
  }
}

/** Returns true if a lead should appear in active queues (dialer index,
 *  /admin/today priority list, etc). Excludes properties where the
 *  trustee sale ran more than 7 days ago — the house has already
 *  foreclosed; we can't help anymore. 7-day grace covers postponed sales
 *  that still show the old date in scraped data. Pre-foreclosure leads
 *  (no sale date) and future-dated sales always pass through. */
export function isLeadActive(lead: DialerInventoryLead): boolean {
  if (!lead.currentSaleDate) return true
  const t = new Date(lead.currentSaleDate).getTime()
  if (Number.isNaN(t)) return true
  const sevenDaysAgoMs = Date.now() - 7 * 24 * 60 * 60 * 1000
  return t > sevenDaysAgoMs
}

export async function findDialerInventoryLead(
  key: string
): Promise<DialerInventoryLead | null> {
  const snapshot = await loadDialerInventory()
  if (!snapshot) return null
  return (
    snapshot.leads.find(
      (l) => l.key === key || l.slug === key || l.leadKey === key || l.vaultSlug === key
    ) ?? null
  )
}

// distressTypeLabel lives in dialer-types.ts (client-safe). Re-export here so
// existing imports keep working.
export { distressTypeLabel } from "@/lib/dialer-types"
