import { readdir, readFile } from "node:fs/promises"
import path from "node:path"

export type OutreachCandidate = {
  track: "auction_partner" | "principal_broker"
  rank: number
  score: number
  organization: string
  contact_name: string
  email: string
  website: string
  domain: string
  city: string
  state: string
  reason: string
  snippet: string
  personalized_line: string
  subject: string
  body: string
  query?: string
}

export type OutreachTrackReport = {
  track: "auction_partner" | "principal_broker"
  generatedAt: string | null
  fileName: string | null
  candidates: OutreachCandidate[]
}

export type OutreachReport = {
  generatedAt: string
  sourceMode: "full" | "fallback"
  sourceNote: string
  sourceDir: string
  tracks: OutreachTrackReport[]
}

const TRACKS: Array<OutreachTrackReport["track"]> = [
  "auction_partner",
  "principal_broker",
]

async function readLatestTrackFile(
  outreachDir: string,
  track: OutreachTrackReport["track"]
): Promise<OutreachTrackReport> {
  const names = await readdir(outreachDir)
  const latest = names
    .filter((name) => name.startsWith(`${track}_`) && name.endsWith(".json"))
    .sort()
    .at(-1)

  if (!latest) {
    return {
      track,
      generatedAt: null,
      fileName: null,
      candidates: [],
    }
  }

  const fullPath = path.join(outreachDir, latest)
  const raw = await readFile(fullPath, "utf8")
  const parsed = JSON.parse(raw) as OutreachCandidate[]
  const generatedAt = latest
    .replace(`${track}_`, "")
    .replace(".json", "")

  return {
    track,
    generatedAt,
    fileName: latest,
    candidates: parsed,
  }
}

async function readTrackFromSnapshot(
  snapshotDir: string,
  track: OutreachTrackReport["track"]
): Promise<OutreachTrackReport> {
  const fileName = `${track}.json`
  const fullPath = path.join(snapshotDir, fileName)
  const raw = await readFile(fullPath, "utf8")
  const parsed = JSON.parse(raw) as OutreachCandidate[]

  return {
    track,
    generatedAt: "snapshot",
    fileName,
    candidates: parsed,
  }
}

export async function getOutreachReport(): Promise<OutreachReport> {
  const outreachDir = path.join(process.cwd(), "..", "falco-distress-bots", "out", "outreach")
  const snapshotDir = path.join(process.cwd(), "data", "outreach")

  try {
    const tracks = await Promise.all(
      TRACKS.map((track) => readLatestTrackFile(outreachDir, track))
    )

    return {
      generatedAt: new Date().toISOString(),
      sourceMode: "full",
      sourceNote:
        "Full outreach mode. Reading the latest review-first auction-partner and principal-broker draft queues from the bots workspace.",
      sourceDir: outreachDir,
      tracks,
    }
  } catch (workspaceError) {
    console.warn("getOutreachReport workspace unavailable, trying hosted snapshot", workspaceError)
  }

  try {
    const tracks = await Promise.all(
      TRACKS.map((track) => readTrackFromSnapshot(snapshotDir, track))
    )

    return {
      generatedAt: new Date().toISOString(),
      sourceMode: "fallback",
      sourceNote:
        "Using the latest hosted outreach snapshot generated by the bots workspace for production-safe review.",
      sourceDir: snapshotDir,
      tracks,
    }
  } catch (error) {
    console.warn("getOutreachReport workspace fallback unavailable", error)
    return {
      generatedAt: new Date().toISOString(),
      sourceMode: "fallback",
      sourceNote:
        "Outreach files are only available in the shared workspace/local environment, and no committed outreach snapshot is present yet.",
      sourceDir: snapshotDir,
      tracks: TRACKS.map((track) => ({
        track,
        generatedAt: null,
        fileName: null,
        candidates: [],
      })),
    }
  }
}
