'use client'

import Link from "next/link"
import { useMemo, useState } from "react"

type OutreachCandidate = {
  track: "auction_partner" | "principal_broker"
  rank: number
  score: number
  organization: string
  contact_name: string
  email: string
  website: string
  domain: string
  city: string
  state: string
  reason: string
  snippet: string
  personalized_line: string
  subject: string
  body: string
  query?: string
}

type OutreachTrackReport = {
  track: "auction_partner" | "principal_broker"
  generatedAt: string | null
  fileName: string | null
  candidates: OutreachCandidate[]
}

type OutreachReport = {
  generatedAt: string
  sourceMode: "full" | "fallback"
  sourceNote: string
  sourceDir: string
  tracks: OutreachTrackReport[]
}

function formatTrackLabel(track: OutreachTrackReport["track"]) {
  return track === "auction_partner" ? "Auction Partners" : "Principal Brokers"
}

export default function OutreachPage() {
  const [secret, setSecret] = useState("")
  const [report, setReport] = useState<OutreachReport | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")

  const totalCandidates = useMemo(() => {
    return report?.tracks.reduce((sum, track) => sum + track.candidates.length, 0) ?? 0
  }, [report])

  async function loadReport() {
    setLoading(true)
    setError("")

    try {
      const res = await fetch("/api/outreach/report", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ secret }),
      })

      const data = await res.json()
      if (!res.ok || !data?.ok) {
        setError(data?.error || "Unable to load outreach queue.")
        return
      }

      setReport(data.report)
    } catch {
      setError("Unable to load outreach queue.")
    } finally {
      setLoading(false)
    }
  }

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="absolute inset-0 -z-20 bg-black" />
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.14),transparent_24%),linear-gradient(to_bottom,rgba(255,255,255,0.03),transparent_16%,transparent_82%,rgba(255,255,255,0.02))]" />

      <section className="mx-auto max-w-7xl px-6 pb-16 pt-12 md:px-10 md:pb-24 md:pt-16">
        <div className="rounded-[32px] border border-white/10 bg-white/[0.045] p-8 shadow-[0_35px_120px_rgba(0,0,0,0.65)] md:p-10">
          <div className="inline-flex rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs uppercase tracking-[0.22em] text-white/55">
            Outreach Queue
          </div>

          <div className="mt-6 grid gap-8 lg:grid-cols-[1.1fr_0.9fr]">
            <div>
              <h1 className="text-4xl font-semibold leading-tight tracking-[-0.04em] md:text-6xl">
                Review the latest partner drafts.
              </h1>

              <p className="mt-5 max-w-2xl text-base leading-7 text-white/68 md:text-lg">
                This page loads the most recent review-first auction-partner and principal-broker
                outreach queues generated by the bots workspace.
              </p>

              {report ? (
                <div className="mt-6 text-sm text-white/45">
                  Generated: {report.generatedAt}
                  <br />
                  Queue size: {totalCandidates}
                  <br />
                  Mode: {report.sourceMode === "full" ? "Workspace outreach queue" : "Fallback"}
                </div>
              ) : null}
            </div>

            <div className="rounded-[28px] border border-white/10 bg-black/40 p-6">
              <div className="text-xs uppercase tracking-[0.22em] text-white/45">
                Internal Access
              </div>

              <div className="mt-5">
                <label className="mb-2 block text-sm text-white/70">Approval Secret</label>
                <input
                  type="password"
                  value={secret}
                  onChange={(e) => setSecret(e.target.value)}
                  className="w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm text-white outline-none placeholder:text-white/30"
                  placeholder="Admin secret"
                />
              </div>

              {error ? (
                <div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200">
                  {error}
                </div>
              ) : null}

              <div className="mt-6 flex flex-wrap gap-3">
                <button
                  onClick={loadReport}
                  disabled={loading}
                  className="inline-flex items-center justify-center rounded-xl bg-white px-6 py-3.5 text-sm font-semibold text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  {loading ? "Loading..." : "Load Outreach Queue"}
                </button>
                <Link
                  href="/operator"
                  className="inline-flex items-center justify-center rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white/80 transition hover:border-white/25 hover:bg-white/10"
                >
                  Operator Console
                </Link>
              </div>
            </div>
          </div>
        </div>

        {report ? (
          <>
            <div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.04] px-5 py-4 text-sm leading-7 text-white/68">
              {report.sourceNote}
              <br />
              Source directory: {report.sourceDir}
            </div>

            <div className="mt-8 grid gap-8">
              {report.tracks.map((track) => (
                <section
                  key={track.track}
                  className="rounded-[28px] border border-white/10 bg-white/[0.045] p-8 shadow-[0_35px_120px_rgba(0,0,0,0.4)]"
                >
                  <div className="flex flex-wrap items-start justify-between gap-4">
                    <div>
                      <div className="text-xs uppercase tracking-[0.22em] text-white/45">
                        {formatTrackLabel(track.track)}
                      </div>
                      <div className="mt-2 text-sm text-white/45">
                        Latest file: {track.fileName || "None found"}
                      </div>
                    </div>

                    <div className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs uppercase tracking-[0.18em] text-white/60">
                      {track.candidates.length} candidates
                    </div>
                  </div>

                  {track.candidates.length ? (
                    <div className="mt-6 grid gap-4">
                      {track.candidates.map((candidate) => (
                        <article
                          key={`${track.track}-${candidate.rank}-${candidate.email}`}
                          className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"
                        >
                          <div className="flex flex-wrap items-start justify-between gap-4">
                            <div>
                              <div className="text-xl font-semibold tracking-[-0.03em] text-white">
                                {candidate.organization}
                              </div>
                              <div className="mt-2 text-sm text-white/55">
                                {[candidate.city, candidate.state].filter(Boolean).join(", ") || "Location unknown"}
                                {" • "}
                                {candidate.domain || "Unknown domain"}
                              </div>
                            </div>

                            <div className="flex flex-wrap gap-2 text-xs uppercase tracking-[0.18em] text-white/70">
                              <span className="rounded-full border border-white/10 bg-white text-black px-3 py-1">
                                Rank {candidate.rank}
                              </span>
                              <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1">
                                Score {candidate.score}
                              </span>
                            </div>
                          </div>

                          <div className="mt-5 grid gap-4 md:grid-cols-4">
                            <div>
                              <div className="text-[11px] uppercase tracking-[0.22em] text-white/40">Email</div>
                              <div className="mt-2 break-all text-sm text-white/82">{candidate.email || "—"}</div>
                            </div>
                            <div>
                              <div className="text-[11px] uppercase tracking-[0.22em] text-white/40">Reason</div>
                              <div className="mt-2 text-sm text-white/82">{candidate.reason || "—"}</div>
                            </div>
                            <div>
                              <div className="text-[11px] uppercase tracking-[0.22em] text-white/40">Subject</div>
                              <div className="mt-2 text-sm text-white/82">{candidate.subject || "—"}</div>
                            </div>
                            <div>
                              <div className="text-[11px] uppercase tracking-[0.22em] text-white/40">Query</div>
                              <div className="mt-2 text-sm text-white/82">{candidate.query || "—"}</div>
                            </div>
                          </div>

                          <div className="mt-5 grid gap-4 lg:grid-cols-[0.95fr_1.05fr]">
                            <div className="rounded-2xl border border-white/10 bg-black/30 p-4">
                              <div className="text-[11px] uppercase tracking-[0.22em] text-white/40">
                                Personalized Line
                              </div>
                              <div className="mt-3 text-sm leading-7 text-white/76">
                                {candidate.personalized_line || "—"}
                              </div>

                              <div className="mt-5 text-[11px] uppercase tracking-[0.22em] text-white/40">
                                Source Snippet
                              </div>
                              <div className="mt-3 text-sm leading-7 text-white/60">
                                {candidate.snippet || "—"}
                              </div>

                              <div className="mt-5 flex flex-wrap gap-3">
                                {candidate.website ? (
                                  <a
                                    href={candidate.website}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="inline-flex items-center justify-center rounded-xl bg-white px-4 py-2 text-sm font-semibold text-black transition hover:bg-white/90"
                                  >
                                    Open Site
                                  </a>
                                ) : null}
                                {candidate.email ? (
                                  <a
                                    href={`mailto:${candidate.email}?subject=${encodeURIComponent(candidate.subject || "")}&body=${encodeURIComponent(candidate.body || "")}`}
                                    className="inline-flex items-center justify-center rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-white/80 transition hover:border-white/25 hover:bg-white/10"
                                  >
                                    Open Draft
                                  </a>
                                ) : null}
                              </div>
                            </div>

                            <div className="rounded-2xl border border-white/10 bg-black/30 p-4">
                              <div className="text-[11px] uppercase tracking-[0.22em] text-white/40">
                                Draft Preview
                              </div>
                              <pre className="mt-3 whitespace-pre-wrap break-words text-sm leading-7 text-white/78">
                                {candidate.body || "—"}
                              </pre>
                            </div>
                          </div>
                        </article>
                      ))}
                    </div>
                  ) : (
                    <div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.035] px-5 py-4 text-sm leading-7 text-white/60">
                      No queue file was found for this track yet in the workspace outreach directory.
                    </div>
                  )}
                </section>
              ))}
            </div>
          </>
        ) : null}
      </section>
    </main>
  )
}
