-- Auto-generated by scripts/migrate-to-unified-leads.mjs
-- One-time migration: vault NDJSON → homeowner_requests
-- Idempotent (upserts on pipeline_lead_key)

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'davidson-county-pre-foreclosure-review-32c4ba30', 'PLAZA RTL TRUST; US BANK NATIONAL ASSOCIATION', 'PLAZA RTL TRUST; US BANK NATIONAL ASSOCIATION', '6183974952', '15456 Old Hickory Blvd, Nashville, TN 37211', 'Davidson County', NULL, 40000, 'TRUSTEE_NOTICE', 3, 3, 3727, 1999, '2025-08-04', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'rutherford-county-pre-foreclosure-review-28a3ea99', 'Cathy Hughes', 'Cathy Hughes', '6159736752', '2050 Alexander Blvd, Murfreesboro, TN 37130', 'Rutherford County', NULL, 420149, 'TRUSTEE_NOTICE', 4, 4, 3780, 2005, '2018-09-21', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'rutherford-county-pre-foreclosure-review-5bc4575b', 'Joseph T Kimberly Woodard', 'Joseph T Kimberly Woodard', '9317970889', '1129 Cotillion Dr., Murfreesboro, TN 37158-1681', 'Rutherford County', NULL, 397000, 'TRUSTEE_NOTICE', 4, 3, 1855, 2017, '2018-03-23', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-187a7afa', 'David Kam', 'David Kam', '9012778870', '24 Summer Grove Rd, Cordova, TN 38018', 'Shelby County', NULL, 248000, 'TRUSTEE_NOTICE', 4, 3, 4551, 1989, '2006-01-31', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-86d2224a', 'TMC GROUP LLC', 'TMC GROUP LLC', '9013787825', '720 Sweetbrier Rd, Memphis, TN 38120', 'Shelby County', NULL, 90000, 'TRUSTEE_NOTICE', 5, 3, 6722, 1974, '2021-06-14', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'mcminn-county-pre-foreclosure-review-507fed70', 'Douglas P Pfeiffer; Linda Pfeiffer', 'Douglas P Pfeiffer; Linda Pfeiffer', '8649933798', '240 Texas Ave, Etowah, TN 37331', 'McMinn County', NULL, 75480, 'TRUSTEE_NOTICE', 4, 2, 1340, 2002, '2025-12-01', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-fffa1e29', 'Brian Dobbins; Neira Dobbins', 'Brian Dobbins; Neira Dobbins', '9015787847', '2225 Brewers Landing, Memphis, TN 38104', 'Shelby County', NULL, 169000, 'TRUSTEE_NOTICE', 2, 2, 1442, 1983, '2004-07-29', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-pre-foreclosure-review-6c6531a4', 'CUMBERLAND RIVER INVESTMENTS LLC', 'CUMBERLAND RIVER INVESTMENTS LLC', '3014667532', '2724 Ann Drive, Clarksville, TN 37040', 'Montgomery County', NULL, 172800, 'TRUSTEE_NOTICE', 3, 3, 1431, 1975, '2025-09-17', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-pre-foreclosure-review-6cca5e55', 'Sarah Kelly', 'Sarah Kelly', '9316488740', '378 Treeland Drive, Clarksville, TN 37040', 'Montgomery County', NULL, 46250, 'TRUSTEE_NOTICE', NULL, 1, 1040, 1977, '1979-02-21', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-pre-foreclosure-review-0990badb', 'Eddie Lee Golliday; Sabine P Golliday', 'Eddie Lee Golliday; Sabine P Golliday', '9312327983', '639 Riversbend Road, Indian Mound, TN 37079', 'Montgomery County', NULL, 230000, 'TRUSTEE_NOTICE', 3, 3, 1549, 1997, '2010-01-08', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'hamilton-county-pre-foreclosure-review-e7cdfff4', 'Michael R Thompson', 'Michael R Thompson', '4235054502', '2106 Ivy St., Chattanooga, TN 37404', 'Hamilton County', NULL, 66930, 'TRUSTEE_NOTICE', 3, 1, 1248, 1999, '2006-08-15', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'knox-county-pre-foreclosure-review-31ca494b', 'SALUDA GRADE LOAN TRUST; US BANK TRUST', 'SALUDA GRADE LOAN TRUST; US BANK TRUST', '6183974952', '4209 Van Dyke Dr, Knoxville, TN 37919', 'Knox County', NULL, 177000, 'TRUSTEE_NOTICE', 3, 2, 944, 1930, '2026-01-16', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-12fac301', 'Christopher Lynn; Karen M Lynn', 'Christopher Lynn; Karen M Lynn', '9014661723', '4794 Bondale Ave, Memphis, TN 38118', 'Shelby County', NULL, 69120, 'TRUSTEE_NOTICE', 3, 2, 1260, 1959, '2026-02-12', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-0fb3e78a', 'METROPOLITAN LIFE INSURANCE COMPANY', 'METROPOLITAN LIFE INSURANCE COMPANY', '6183974952', '2601 Dakar Ave, Memphis, TN 38127', 'Shelby County', NULL, 20000, 'TRUSTEE_NOTICE', 3, 1, 864, 1960, '2025-02-06', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-0a84de49', 'BARCLAYS MORTGAGE LOAN TRUST; CITIBANK NA', 'BARCLAYS MORTGAGE LOAN TRUST; CITIBANK NA', '6183974952', '5089 Leonard Rd, Memphis, TN 38109', 'Shelby County', NULL, 42400, 'TRUSTEE_NOTICE', 3, 1, 1240, 1968, '2025-10-09', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-ccfdfbd8', 'Joseph Simon', 'Joseph Simon', '9016501572', '3797 Eddington Cove, Memphis, TN 38125', 'Shelby County', NULL, 116619, 'TRUSTEE_NOTICE', 3, 2, 1822, 1977, '2007-01-31', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-dd1a07a6', 'LEGACY MORTGAGE ASSET TRUST; U S BANK TRUST', 'LEGACY MORTGAGE ASSET TRUST; U S BANK TRUST', '9012796220', '1624 Winfield Ave, Memphis, TN 38116', 'Shelby County', NULL, 30000, 'TRUSTEE_NOTICE', 2, 2, 1001, 1959, '2025-11-10', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-691c1ae0', 'MLHOUSING LLC', 'MLHOUSING LLC', '9012831015', '1654 Ely St, Memphis, TN 38106', 'Shelby County', NULL, 75000, 'TRUSTEE_NOTICE', 3, 1, 850, 1958, '2023-11-09', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-da8d9d70', 'METROPOLITAN TOWER LIFE INSURANCE C', 'METROPOLITAN TOWER LIFE INSURANCE C', '6183974952', '6362 Martinwood Dr., Millington, TN 38053', 'Shelby County', NULL, 87000, 'TRUSTEE_NOTICE', 3, 1, 1401, 1976, '2025-12-05', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-3f275453', 'Juan M Brooks', 'Juan M Brooks', '9018644145', '2310 Boyle Avenue, Memphis, TN 38114', 'Shelby County', NULL, 52000, 'TRUSTEE_NOTICE', 3, 2, 1144, 1925, '2007-06-28', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-pre-foreclosure-review-a77709b9', 'Reginald Banyon', 'Reginald Banyon', '9013461986', '954 Linwood Road, Memphis, TN 38116', 'Shelby County', NULL, 71773, 'TRUSTEE_NOTICE', 4, 1, 2691, 1957, '2004-08-30', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'morgan-county-pre-foreclosure-review-05b73e5c', 'NATIONSTAR MORTGAGE LLC', 'NATIONSTAR MORTGAGE LLC', '7706934495', '655 Coal Hill Rd, Harriman, TN 37748', 'Morgan County', NULL, 79378, 'TRUSTEE_NOTICE', 2, 1, 680, 1940, '2026-01-23', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'madison-county-pre-foreclosure-review-a34e8f8a', 'ALVIN U NARNEY', 'ALVIN U NARNEY', '7316863280', '54 Crestwood Dr., Jackson, TN 38305', 'Madison County', NULL, 88369, 'TRUSTEE_NOTICE', NULL, 1, 2155, 1978, '2017-03-24', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'sullivan-county-pre-foreclosure-review-cd1d48f6', 'QUINT BOURGEOIS', 'QUINT BOURGEOIS', '4235437801', '592 Emmett Road, Bristol, TN 37620', 'Sullivan County', NULL, 91414, 'TRUSTEE_NOTICE', NULL, NULL, NULL, NULL, NULL, 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'hamilton-county-pre-foreclosure-review-84d90642', 'Elizabeth Owens', 'Elizabeth Owens', '7574422584', '208 N Saint Marks Ave, Chattanooga, TN 37411', 'Hamilton County', NULL, 282865, 'TRUSTEE_NOTICE', 3, 2, 1736, 1945, '2023-11-03', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'hamilton-county-pre-foreclosure-review-2e6d37b4', 'KALI & KALI LLC', 'KALI & KALI LLC', '6183974952', '4212 Rogers Rd, Chattanooga, TN 37411', 'Hamilton County', NULL, 392000, 'TRUSTEE_NOTICE', 5, 3, 4227, 1959, '2022-03-30', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'marshall-county-pre-foreclosure-review-b943e26f', 'GOOD NEIGHBOR APARTMENTS LLC', 'GOOD NEIGHBOR APARTMENTS LLC', '6155504200', '111 W Commerce St., Lewisburg, TN 37091', 'Marshall County', NULL, 650000, 'TRUSTEE_NOTICE', NULL, 3, 10398, 1963, '2021-08-26', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'rutherford-county-foreclosure-a99c2e63', 'ETHAN T CZEREDA', 'ETHAN T CZEREDA', '9104364439', '1313 Fall Parkway, Murfreesboro, TN 37129,', 'Rutherford County', '2026-05-12', 180900, 'TRUSTEE_NOTICE', 3, 3, 1694, 2006, '2019-05-08', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'davidson-county-foreclosure-f6560628', 'FRNDZ VENTURE CAPITAL CORP', 'FRNDZ VENTURE CAPITAL CORP', '6154854985', '104 Creighton Ave Nashville, TN 37206', 'Davidson County', '2026-05-14', 25000, 'TRUSTEE_NOTICE', 3, 2, 1825, 1940, '2026-03-13', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'rutherford-county-foreclosure-6ee64b5c', 'JAKE MCCRACKEN', 'JAKE MCCRACKEN', '4805162562', '187 Elizabeth Drive, Murfreesboro, TN 37128', 'Rutherford County', '2026-05-26', 505000, 'TRUSTEE_NOTICE', 4, 3, 2880, 1988, '2021-12-03', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'davidson-county-foreclosure-9b98ed9a', 'DINESH KUMAR PATEL', 'DINESH KUMAR PATEL', '2622516512', '1409 Scarcroft Lane, Nashville, TN 37221', 'Davidson County', '2026-06-15', 211531, 'TRUSTEE_NOTICE', 4, 3, 2228, 2014, '2014-08-12', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'davidson-county-foreclosure-2b20ff74', 'James Sampson', 'James Sampson', '9096001338', '4864 Peppertree Drive, Antioch, TN 37013', 'Davidson County', '2026-04-30', 191250, 'TRUSTEE_NOTICE', 4, 3, 1833, 1993, '2021-05-04', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'rutherford-county-foreclosure-decb8029', 'Nizar Lalani; Jessani Mywish', 'Nizar Lalani; Jessani Mywish', '6154240919', '303 Kirtley Ct, Murfreesboro, TN, Murfreesboro, TN 37130', 'Rutherford County', '2026-05-05', 13185, 'TRUSTEE_NOTICE', NULL, 3, 2158, 1996, '2003-12-11', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'davidson-county-foreclosure-b664bdae', 'KAREN TATE', 'KAREN TATE', '4145279427', '3408 HOPE COVE, NASHVILLE, TN 37217', 'Davidson County', '2026-04-16', 158400, 'TRUSTEE_NOTICE', 3, 2, 1843, 2005, '2006-01-03', 98)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'davidson-county-foreclosure-96f145db', 'Gertrude Collier; Quanisha Booker', 'Gertrude Collier; Quanisha Booker', '6154918147', '817 Joseph Avenue, Nashville, TN 37207', 'Davidson County', '2026-04-23', 22400, 'TRUSTEE_NOTICE', 2, 1, 1525, 1966, '2025-06-20', 98)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'rutherford-county-foreclosure-5b9d9f7c', 'Destinie La Quittia Akins', 'Destinie La Quittia Akins', '6154711962', '180 Center Street, Lavergne, TN 37086,', 'Rutherford County', '2026-04-21', 102400, 'TRUSTEE_NOTICE', NULL, 2, 1082, 2002, '2025-11-07', 98)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'lawrence-county-foreclosure-d70be4d8', 'Zachary A Keane', 'Zachary A Keane', '2566843886', '1604 Hilltop Drive, Lawrenceburg, TN 38464,', 'Lawrence County', '2026-05-12', 175757, 'TRUSTEE_NOTICE', 4, 2, 1352, 1972, '2019-12-12', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-foreclosure-249eda5d', 'JAMES LEMAR HILL', 'JAMES LEMAR HILL', '4083077693', '2618 UNION HALL RD, CLARKSVILLE, TN 37040', 'Montgomery County', '2026-05-12', 275000, 'TRUSTEE_NOTICE', 4, 1, 1050, 1981, '2022-06-17', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-foreclosure-9a6d28dc', 'Molly Filipovich', 'Molly Filipovich', '9318023548', '2897 Sharpie Drive, Clarksville, TN 37040', 'Montgomery County', '2026-05-13', 256500, 'TRUSTEE_NOTICE', 3, 3, 1869, 2009, '2021-10-15', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-foreclosure-6ff7daff', 'Nannie C Walker; Nicole Mayhorn', 'Nannie C Walker; Nicole Mayhorn', '9012468337', '10481 MABRY MILL ROAD, CORDOVA, TN 38016', 'Shelby County', '2026-05-14', 40000, 'TRUSTEE_NOTICE', 4, 3, 4111, 2006, '2006-12-01', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'knox-county-foreclosure-ac4ed8cb', 'Kenneth R Harris; Robin D Harris', 'Kenneth R Harris; Robin D Harris', '8659921221', '7308 OAK LEAF ROAD, KNOXVILLE, TN 37918', 'Knox County', '2026-05-14', 27100, 'TRUSTEE_NOTICE', 3, 1, 960, 1988, '2004-04-21', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'franklin-county-foreclosure-1c89f1f3', 'Nancy Hendleman; Margaret A Hendleman', 'Nancy Hendleman; Margaret A Hendleman', '7708267788', '2308 Eastbrook Road, Estill Springs, TN 37330', 'Franklin County', '2026-06-09', 367500, 'TRUSTEE_NOTICE', 4, 2, 2127, 1971, '2021-09-15', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'knox-county-foreclosure-94b7fb7a', 'BILLIE WOODRUFF', 'BILLIE WOODRUFF', '8654432671', '1411 Dick Lonas Road, Knoxville, TN 37909', 'Knox County', '2026-06-11', 213900, 'TRUSTEE_NOTICE', 3, 2, 1536, 2006, '2025-04-02', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'cumberland-county-foreclosure-af21e5dd', 'Carol Helena Casey', 'Carol Helena Casey', '7067573704', '59 Hidden Hollow Circle, Crossville, TN 38571', 'Cumberland County', '2026-06-17', 119500, 'TRUSTEE_NOTICE', 3, 2, 1652, 2000, '2018-12-13', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'hamilton-county-foreclosure-019d3ecb', 'WILLIAM HITCHCOCK', 'WILLIAM HITCHCOCK', '8157327232', '1306 Coleman Circle, East Ridge, TN 37412', 'Hamilton County', '2026-05-21', 112000, 'TRUSTEE_NOTICE', 3, 1, 1492, 1960, '2015-09-19', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'shelby-county-foreclosure-f52a28ee', 'Christopher B Smith; Latasha Spight', 'Christopher B Smith; Latasha Spight', '7864752543', '4765 King Everett Cove, Lakeland, TN 38002', 'Shelby County', '2026-04-30', 538350, 'TRUSTEE_NOTICE', 5, 4, 4924, 2021, '2021-12-15', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'lawrence-county-foreclosure-3ba10ecf', 'John E Williams; Melody R Williams', 'John E Williams; Melody R Williams', '5097542828', '501 1st Street, Lawrenceburg, TN 38464', 'Lawrence County', '2026-04-30', 274829, 'TRUSTEE_NOTICE', 3, 2, 1544, 1952, '2024-02-14', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-foreclosure-3ccb8b8c', 'Syrshannon W Jones', 'Syrshannon W Jones', '9314948727', '538 Oakmont Drive, Clarksville, TN 37042', 'Montgomery County', '2026-04-30', 110455, 'TRUSTEE_NOTICE', 3, 2, 1025, 2008, '2023-08-11', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'sumner-county-foreclosure-51329846', 'Jeffrey T Abner; Tiffany L Abner', 'Jeffrey T Abner; Tiffany L Abner', '6158717330', '111 Longboat Court, Gallatin, TN 37066', 'Sumner County', '2026-04-30', 276800, 'TRUSTEE_NOTICE', NULL, 3, 2189, 2003, '2010-12-28', 100)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-foreclosure-0f99caa2', 'Sean Driscoll', 'Sean Driscoll', '2073125543', '3434 MELROSE DRIVE, CLARKSVILLE, TN 37042', 'Montgomery County', '2026-04-15', 83200, 'TRUSTEE_NOTICE', NULL, 2, 1261, 1994, '2006-08-25', 98)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'williamson-county-foreclosure-042fffa7', 'Lauren Luna Caputo; William Allen Caputo', 'Lauren Luna Caputo; William Allen Caputo', '6157398989', '1014 Scouting Drive, Franklin, TN 37064', 'Williamson County', '2026-04-15', 360000, 'TRUSTEE_NOTICE', NULL, 2, 2668, 2017, '2017-07-26', 98)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;

insert into public.homeowner_requests (source, pipeline_lead_key, full_name, owner_name_records, phone, property_address, county, trustee_sale_date, mortgage_balance, distress_type, beds, baths, sqft, year_built, last_sale_date, pipeline_score) values ('bot', 'montgomery-county-foreclosure-20a46a35', 'Jonathan J Benka; Nancy F Benka', 'Jonathan J Benka; Nancy F Benka', '2708398332', '314 SOUTHERN DRIVE, CLARKSVILLE, TN 37042', 'Montgomery County', '2026-04-21', 85850, 'TRUSTEE_NOTICE', 3, 2, 1202, 1987, '2021-08-11', 98)
  on conflict (pipeline_lead_key) where pipeline_lead_key is not null do update set
        full_name = excluded.full_name,
        owner_name_records = excluded.owner_name_records,
        phone = excluded.phone,
        property_address = excluded.property_address,
        county = excluded.county,
        trustee_sale_date = excluded.trustee_sale_date,
        mortgage_balance = excluded.mortgage_balance,
        distress_type = excluded.distress_type,
        beds = excluded.beds,
        baths = excluded.baths,
        sqft = excluded.sqft,
        year_built = excluded.year_built,
        last_sale_date = excluded.last_sale_date,
        pipeline_score = excluded.pipeline_score;
